backend:
  name: git-gateway
  branch: main

media_folder: static/images/uploads
public_folder: /images/uploads

display_url: https://example.com
logo_url: https://example.com/images/logo.png

collections:
  - name: "content"
    label: "Content"
    delete: false
    editor:
      preview: false
    files:
      - name: "data"
        label: "Data"
        file: "cms/data.json"
        fields:
          - { name: "domainName", label: "Domain Name", widget: "string" }
          - { name: "email", label: "Email", widget: "string" }
          - { name: "phone", label: "Phone Number", widget: "string" }
          - { name: "phoneRaw", label: "Phone Number Raw", widget: "string" }
          - { name: "seoDescription", label: "SEO Description", widget: "text" }
          - { name: "seoTitle", label: "SEO Title", widget: "string" }
          - { name: "heroTitle", label: "Hero Title", widget: "string" }
          - { name: "heroSubtitle", label: "Hero Subtitle", widget: "string" }
          - { name: "heroCallUsButtonText", label: "Hero Call Us Button Text", widget: "string" }
          - { name: "heroEmailUsButtonText", label: "Hero Email Us Button Text", widget: "string" }
          - { name: "contentIntro", label: "Content Intro", widget: "text" }
